ordering:
  inicio: ''
  vestidos: ''
  conjuntos: ''
  bebitas: ''
  calzado: ''
items:
  inicio:
    id: 101
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  vestidos:
    id: 109
    rel: ''
  conjuntos:
    id: 110
    rel: ''
  bebitas:
    id: 111
    rel: ''
  calzado:
    id: 125
    rel: ''
