name: '9'
timestamp: 1612290675
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1611523371
positions:
  pie-pag1: 'Module Position'
  pie-pag2: 'Module Position'
  pie-pag3: 'Module Position'
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8836: 'Logo / Image'
  menu:
    menu-2917: Menu
  messages:
    system-messages-4327: 'System Messages'
  content:
    system-content-7173: 'Page Content'
  branding:
    branding-7678: Branding
  position:
    position-position-1649: 'Module Position'
    position-position-4986: 'Module Position'
    position-position-3372: 'Module Position'
  copyright:
    copyright-6949: Copyright
  mobile-menu:
    mobile-menu-2651: Mobile-menu
inherit:
  default:
    offcanvas: offcanvas
    mobile-menu-2651: mobile-menu-4430
