name: _error
timestamp: 1611523067
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1611523067
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7710: Logo
  spacer:
    spacer-7265: Spacer
    spacer-3193: Spacer
  menu:
    menu-1574: Menu
  content:
    system-content-8959: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-3464: Copyright
  branding:
    branding-3237: Branding
  mobile-menu:
    mobile-menu-6738: Mobile-menu
inherit: {  }
