version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1611523067
layout:
  /header/:
    -
      - 'logo-7710 30'
      - 'spacer-7265 70'
  /navigation/:
    -
      - menu-1574
  /main/:
    -
      - system-content-8959
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3464 40'
      - 'spacer-3193 30'
      - 'branding-3237 30'
  offcanvas:
    -
      - mobile-menu-6738
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
