name: _offline
timestamp: 1611523067
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1611523067
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-3943: Logo
  spacer:
    spacer-1443: Spacer
    spacer-9350: Spacer
  messages:
    system-messages-7702: 'System Messages'
  content:
    system-content-7569: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-5531: Copyright
  branding:
    branding-1863: Branding
inherit: {  }
