version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1611523067
layout:
  /header/:
    -
      - 'logo-3943 30'
      - 'spacer-1443 70'
  /main/:
    -
      - system-messages-7702
    -
      - system-content-7569
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5531 40'
      - 'spacer-9350 30'
      - 'branding-1863 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
