name: _body_only
timestamp: 1611523067
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1611523067
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-9083: 'System Messages'
  content:
    system-content-8930: 'Page Content'
inherit: {  }
