version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1611523067
layout:
  /main/:
    -
      - system-messages-9083
    -
      - system-content-8930
structure:
  main:
    attributes:
      boxed: ''
